export { default as Navbar } from './Navbar/Navbar';
export { default as Info } from './Info/Info';
export { default as Offer } from './Offer/Offer';
export { default as SingleOffer } from './Offer/SingleOffer/SingleOffer';
export { default as SingleOfferDetails } from './Offer/SingleOfferDetails/SingleOfferDetails';
export { default as Projects } from './Projects/Projects';
export { default as SingleProjectDetails } from './Projects/SingleProjectDetails/SingleProjectDetails'
export { default as Form } from './Form/Form'
export { default as Footer } from './FooterComponent/FooterComponent'
export { default as Home } from './Home/Home'